/**
 * LOGIN ACTIONS
 */
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
/**
 * FETCH ACTIONS
 */
export const FETCH_DATA_STARTED = "FETCH_DATA_STARTED";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const FETCH_DATA = "FETCH_DATA";
/**
 * POST ACTIONS
 */
export const POST_DATA_STARTED = "POST_DATA_STARTED";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAILED = "POST_DATA_FAILED";
export const POST_DATA_INIT = "POST_DATA_INIT";
export const UPDATE_POST_STATUS = "UPDATE_POST_STATUS";
/**
 * ERROR ACTIONS
 */
export const NETWORK_ERROR = 'NETWORK_ERROR'
export const HTTP_404_ERROR = 'HTTP_404_ERROR';
export const HTTP_500_ERROR = 'HTTP_500_ERROR';
export const HTTP_OTHER_ERROR = 'HTTP_OTHER_ERROR';
