export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const FETCH_DATA_STARTED = "FETCH_DATA_STARTED";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const FETCH_DATA = "FETCH_DATA";

export const POST_DATA_STARTED = "POST_DATA_STARTED";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAILED = "POST_DATA_FAILED";
export const POST_DATA_INIT = "POST_DATA_INIT";
export const UPDATE_POST_STATUS = "UPDATE_POST_STATUS";
